### ISSUE TITLE
Shadows on entities bugging out.

### ISSUE THREAD

**Issue by jacobvdl** [SydMontague/ImageMaps#48]
Hey, I have been receiving complains that shadows are being glitchy on mobs and beds. We only started getting this after adding the ImageMaps plugin. We have a lot of images on the server as it is setup so everyone can use it.
Recording of the bug:

https://user-images.githubusercontent.com/46667568/133042392-aef30534-c6e0-403f-8c16-5917e3768fac.mp4

The server is running paper 1.17.1

**Comment by SydMontague** [comment]
Have you tried removing the plugin to see if the issue is gone?

There should be absolutely no way the plugin is causing this, all interactions it does with the world are indistinguishable from vanilla Minecraft and it doesn't do anything related to entities besides item frames.

Even more so, shadows should be a client thing, so I'd rather suspect client mods.

**Comment by jacobvdl** [comment]
We do have hundreds of maps in one area so that could be one of the issues, I will try load up vanilla minecraft to see if that works.

**Comment by jacobvdl** [comment]
Ah, it was just a bug with optifine that is probably related to the amount of item frames and maps.
