### ISSUE TITLE
Server transfer onto new OS caused maps to not load properly

### ISSUE THREAD

**Issue by SteveDaBartender** [SydMontague/ImageMaps#51]
Hello, I recently moved my server to a new operating system (from Ubuntu 20 to Windows 10), and updated to the newest version of the plugin, and after the transfer the maps that existed in the world appear as either blank or other maps. The map files appear to be in the plugins folder and I can still place them and download new maps. I am running on Paper MC 1.17.1 .

**Comment by SydMontague** [comment]
Please check whether the image files on your server are still openable by regular image viewing programs.

Your images files have most likely been corrupted in the transfer by some software involved by it treating the image files as text instead of a binary file. Please check your transfer client's settings to make sure it is working in binary mode.

**Comment by SteveDaBartender** [comment]
It seems that the images did lose their extensions, as well as the file containing the maps being corrupted too. Restoring a backup of the plugin settings seems to have worked. Thank you for the help.
